### ISSUE TITLE
不修改dic.py的情况下执行报错

### ISSUE THREAD

**Issue by RAINighty** [1250422131/LastOrderBot#2]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\LastOrderBot-master\__init__.py", line 8, in runON
    run.run()
  File "C:\Users\Administrator\Desktop\LastOrderBot-master\plugin\run.py", line 57, in run
    newMsg = demjson.decode(newMsgGet.text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\demjson.py", line 2039, in dec
de
    j = JSON( strict=strict )
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\demjson.py", line 910, in __in
t__
    self._asciiencodable = [32 <= c < 128 and not self._rev_escapes.has_key(chr(c))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\demjson.py", line 910, in <lis
comp>
    self._asciiencodable = [32 <= c < 128 and not self._rev_escapes.has_key(chr(c))
AttributeError: 'dict' object has no attribute 'has_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\LastOrderBot-master\__init__.py", line 8, in runON
    run.run()
  File "C:\Users\Administrator\Desktop\LastOrderBot-master\plugin\run.py", line 57, in run
    newMsg = demjson.decode(newMsgGet.text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\demjson.py", line 2039, in dec
de
    j = JSON( strict=strict )
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\demjson.py", line 910, in __in
t__
    self._asciiencodable = [32 <= c < 128 and not self._rev_escapes.has_key(chr(c))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\demjson.py", line 910, in <lis
comp>
    self._asciiencodable = [32 <= c < 128 and not self._rev_escapes.has_key(chr(c))
AttributeError: 'dict' object has no attribute 'has_key'

**Comment by RAINighty** [comment]
已经解决

**Comment by 1250422131** [comment]
我看到了你的反馈，这个问题是没有安装模块导致的，请先安装所需模块。

**Comment by 1250422131** [comment]
另外，运行的文件夹需要是项目的根目录文件夹
